'use client';
import {useMemo,useState} from 'react';
import {BarChart3,Box,BriefcaseBusiness,ChevronDown,CircleDollarSign,ClipboardList,CreditCard,FileBarChart,History,Home,Menu,PackagePlus,Percent,Plus,Receipt,Search,Settings,ShoppingCart,Store,Truck,Users,WalletCards,X,Minus,Trash2,Printer,LogOut} from 'lucide-react';

const seed=[
{id:'P001',barcode:'100001',name:'Mineral Water 500ml',category:'General',brand:'Local',supplier:'Main Supplier',cost:70,price:120,wholesale:105,stock:48,min:10,max:100,unit:'pcs'},
{id:'P002',barcode:'100002',name:'Soft Drink 1L',category:'General',brand:'Local',supplier:'Main Supplier',cost:210,price:320,wholesale:290,stock:24,min:8,max:60,unit:'pcs'},
{id:'P003',barcode:'100003',name:'Chocolate Bar',category:'Gifts',brand:'Premium',supplier:'Main Supplier',cost:150,price:250,wholesale:220,stock:35,min:8,max:70,unit:'pcs'},
{id:'P004',barcode:'100004',name:'Shampoo 200ml',category:'Cosmetics',brand:'Care',supplier:'Main Supplier',cost:420,price:650,wholesale:590,stock:14,min:4,max:40,unit:'pcs'}
];
const cats=['All','Electronics','Home Appliances','Gifts','Cosmetics','Perfumes','Watches','Accessories','General'];
const money=n=>`Rs. ${Number(n||0).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function App(){
 const [page,setPage]=useState('Dashboard'),[products,setProducts]=useState(seed),[sales,setSales]=useState([]),[expenses,setExpenses]=useState([]),[cart,setCart]=useState([]),[search,setSearch]=useState(''),[cat,setCat]=useState('All'),[discount,setDiscount]=useState(0),[discountMode,setDiscountMode]=useState('%'),[pay,setPay]=useState('Cash'),[cash,setCash]=useState(''),[customer,setCustomer]=useState('Walk-in Customer'),[showMenu,setShowMenu]=useState(false),[showProduct,setShowProduct]=useState(false),[receipt,setReceipt]=useState(null);
 const filtered=products.filter(p=>(cat==='All'||p.category===cat)&&(`${p.name} ${p.barcode}`.toLowerCase().includes(search.toLowerCase())));
 const subtotal=cart.reduce((a,i)=>a+i.price*i.qty,0),discountValue=discountMode==='%'?subtotal*Number(discount||0)/100:Number(discount||0),total=Math.max(0,subtotal-discountValue),change=Math.max(0,Number(cash||0)-total);
 const todaySales=sales.reduce((a,s)=>a+s.total,0),todayCost=sales.reduce((a,s)=>a+s.cost,0),todayExpenses=expenses.reduce((a,e)=>a+e.amount,0);
 const checkout=()=>{if(!cart.length)return;const s={id:`INV-${Date.now().toString().slice(-7)}`,date:new Date(),customer,items:cart,total,subtotal,discount:discountValue,payment:pay,cash:Number(cash||0),change,cost:cart.reduce((a,i)=>a+i.cost*i.qty,0)};setSales(v=>[s,...v]);setProducts(ps=>ps.map(p=>{const i=cart.find(x=>x.id===p.id);return i?{...p,stock:p.stock-i.qty}:p}));setReceipt(s);setCart([]);setCash('');setDiscount(0)};
 return <div className="shell">
  <header><div className="brand"><div className="logo">S</div><div><b>SmartPOS</b><small>Professional Retail POS & Inventory System</small></div></div><button className="menub" onClick={()=>setShowMenu(!showMenu)}><Menu/></button><div className="user">Admin <span>Owner</span></div></header>
  <div className="body">
   <aside className={showMenu?'open':''}>{<Nav icon={<Home/>} t="Dashboard" p={page} go={setPage}/>}<Nav icon={<ShoppingCart/>} t="POS" p={page} go={setPage}/><Nav icon={<Box/>} t="Inventory" p={page} go={setPage}/><Nav icon={<ClipboardList/>} t="Purchases" p={page} go={setPage}/><Nav icon={<Truck/>} t="Suppliers" p={page} go={setPage}/><Nav icon={<Users/>} t="Customers" p={page} go={setPage}/><Nav icon={<WalletCards/>} t="Expenses" p={page} go={setPage}/><Nav icon={<History/>} t="Sales History" p={page} go={setPage}/><Nav icon={<FileBarChart/>} t="Reports" p={page} go={setPage}/><Nav icon={<Settings/>} t="Settings" p={page} go={setPage}/><div className="sidefoot">Single Shop · LKR<br/>Cloud-ready architecture</div></aside>
   <main>{page==='Dashboard'&&<Dashboard sales={sales} products={products} expenses={expenses} money={money}/>}
   {page==='POS'&&<POS {...{filtered,search,setSearch,cat,setCat,cart,setCart,subtotal,discount,setDiscount,discountMode,setDiscountMode,total,pay,setPay,cash,setCash,customer,setCustomer,change,checkout,money,cats,receipt,setReceipt}}/>}
   {page==='Inventory'&&<Inventory products={products} setProducts={setProducts} money={money} show={showProduct} setShow={setShowProduct}/>}
   {['Purchases','Suppliers','Customers','Expenses','Sales History','Reports','Settings'].includes(page)&&<Module page={page} sales={sales} products={products} expenses={expenses} setExpenses={setExpenses} money={money}/>}
   </main>
  </div>
 </div>
}

function Nav({icon,t,p,go}){return <button className={p===t?'nav active':'nav'} onClick={()=>go(t)}>{icon}<span>{t}</span></button>}
function Head({title,sub,action}){return <div className="head"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Dashboard({sales,products,expenses,money}){
 const salesTotal=sales.reduce((a,s)=>a+s.total,0),cost=sales.reduce((a,s)=>a+s.cost,0),low=products.filter(p=>p.stock<=p.min).length,out=products.filter(p=>p.stock<=0).length;
 const payments=['Cash','Card','Bank Transfer','Credit'].map(x=>[x,sales.filter(s=>s.payment===x).reduce((a,s)=>a+s.total,0)]);
 return <><Head title="Dashboard" sub="Today's shop performance at a glance." action={<button className="primary">Export Report</button>}/><div className="cards">
  <Metric t="Today's Sales" v={money(salesTotal)} icon={<CircleDollarSign/>}/><Metric t="Today's Bills" v={sales.length} icon={<Receipt/>}/><Metric t="Today's Profit" v={money(salesTotal-cost-expenses.reduce((a,e)=>a+e.amount,0))} icon={<BarChart3/>}/><Metric t="Total Products" v={products.length} icon={<Box/>}/>
  <Metric t="Stock Value" v={money(products.reduce((a,p)=>a+p.stock*p.cost,0))} icon={<PackagePlus/>}/><Metric t="Low Stock" v={low} icon={<PackagePlus/>}/><Metric t="Out of Stock" v={out} icon={<Box/>}/><Metric t="Expenses" v={money(expenses.reduce((a,e)=>a+e.amount,0))} icon={<WalletCards/>}/>
 </div><div className="grid2"><div className="panel"><h2>Sales Summary</h2><div className="periods"><b>Today<br/><strong>{money(salesTotal)}</strong></b><b>Yesterday<br/><strong>Rs. 0.00</strong></b><b>This Week<br/><strong>{money(salesTotal)}</strong></b><b>This Month<br/><strong>{money(salesTotal)}</strong></b></div><div className="chart">{[30,55,42,78,60,88,70,96].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div><div className="panel"><h2>Payment Breakdown</h2>{payments.map(([x,v])=><div className="payrow" key={x}><span>{x}</span><b>{money(v)}</b></div>)}</div></div></>
}
function Metric({t,v,icon}){return <div className="metric"><span>{icon}</span><small>{t}</small><b>{v}</b></div>}
function POS(p){
 return <><Head title="Point of Sale" sub="Fast checkout for your shop."/><div className="pos">
 <div className="panel catalog"><div className="search"><Search/><input value={p.search} onChange={e=>p.setSearch(e.target.value)} placeholder="Search product or barcode"/></div><div className="chips">{p.cats.map(c=><button className={p.cat===c?'chip active':'chip'} onClick={()=>p.setCat(c)} key={c}>{c}</button>)}</div><div className="products">{p.filtered.map(x=><button className="prod" key={x.id} onClick={()=>p.setCart(c=>{let f=c.find(i=>i.id===x.id);return f?c.map(i=>i.id===x.id?{...i,qty:i.qty+1}:i):[...c,{...x,qty:1}]})}><div className="pic"><Box/></div><b>{x.name}</b><small>{x.barcode} · Stock {x.stock}</small><strong>{p.money(x.price)}</strong></button>)}</div></div>
 <div className="panel checkout"><div className="checkouthead"><h2>Current Invoice</h2><button onClick={()=>p.setCart([])}>Clear</button></div>{!p.cart.length?<div className="empty"><ShoppingCart/><b>No items</b><span>Add products to begin.</span></div>:<div className="cart">{p.cart.map(i=><div className="cartrow" key={i.id}><div><b>{i.name}</b><small>{p.money(i.price)} × {i.qty}</small></div><div className="qty"><button onClick={()=>p.setCart(c=>c.map(x=>x.id===i.id?{...x,qty:Math.max(1,x.qty-1)}:x))}><Minus/></button><b>{i.qty}</b><button onClick={()=>p.setCart(c=>c.map(x=>x.id===i.id?{...x,qty:x.qty+1}:x))}><Plus/></button><button className="danger" onClick={()=>p.setCart(c=>c.filter(x=>x.id!==i.id))}><Trash2/></button></div></div>)}</div>}
 <div className="summary"><label>Customer<select value={p.customer} onChange={e=>p.setCustomer(e.target.value)}><option>Walk-in Customer</option><option>Credit Customer</option></select></label><div><span>Subtotal</span><b>{p.money(p.subtotal)}</b></div><div className="disc"><span>Discount</span><input type="number" value={p.discount} onChange={e=>p.setDiscount(e.target.value)}/><select value={p.discountMode} onChange={e=>p.setDiscountMode(e.target.value)}><option>%</option><option>Rs.</option></select></div><div className="total"><span>Grand Total</span><b>{p.money(p.total)}</b></div><div className="methods">{['Cash','Card','Bank Transfer','Credit'].map(x=><button className={p.pay===x?'active':''} onClick={()=>p.setPay(x)} key={x}>{x}</button>)}</div>{p.pay==='Cash'&&<label>Cash Received<input type="number" value={p.cash} onChange={e=>p.setCash(e.target.value)} placeholder="0.00"/><small>Change: {p.money(p.change)}</small></label>}<div className="actions"><button className="hold">Hold Sale</button><button className="primary" disabled={!p.cart.length} onClick={p.checkout}>Complete Sale</button></div></div></div>{p.receipt&&<Modal title="Receipt" close={()=>p.setReceipt(null)}><ReceiptView s={p.receipt} money={p.money}/><button className="primary full" onClick={()=>window.print()}><Printer/> Print Receipt</button></Modal>}</>
}
function Inventory({products,setProducts,money,show,setShow}){const [f,setF]=useState({name:'',barcode:'',category:'General',cost:'',price:'',stock:'',min:'5'});return <><Head title="Inventory" sub="Products, stock levels and margins." action={<button className="primary" onClick={()=>setShow(true)}><Plus/> Add Product</button>}/><div className="panel table"><table><thead><tr><th>Product</th><th>Barcode</th><th>Category</th><th>Cost</th><th>Selling</th><th>Stock</th><th>Margin</th><th>Status</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.barcode}</td><td>{p.category}</td><td>{money(p.cost)}</td><td>{money(p.price)}</td><td>{p.stock}</td><td>{p.price?(((p.price-p.cost)/p.price)*100).toFixed(1):0}%</td><td><span className={p.stock<=p.min?'bad':'good'}>{p.stock<=0?'Out':p.stock<=p.min?'Low':'OK'}</span></td></tr>)}</tbody></table></div>{show&&<Modal title="Add Product" close={()=>setShow(false)}><div className="form">{Object.entries({name:'Product Name',barcode:'Barcode',category:'Category',cost:'Cost Price',price:'Selling Price',stock:'Current Stock',min:'Minimum Stock'}).map(([k,l])=><label key={k}>{l}<input value={f[k]} type={['cost','price','stock','min'].includes(k)?'number':'text'} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div><button className="primary full" onClick={()=>{setProducts(v=>[...v,{id:`P${Date.now()}`,...f,cost:Number(f.cost),price:Number(f.price),stock:Number(f.stock),min:Number(f.min),wholesale:Number(f.price),max:100,unit:'pcs',brand:'',supplier:''}]);setShow(false)}}>Save Product</button></Modal>}</>}
function Module({page,sales,products,expenses,setExpenses,money}){let title=page;let sub={Purchases:'Receive stock and track supplier purchases.',Suppliers:'Supplier contacts, purchases and balances.',Customers:'Customers, credit limits and outstanding balances.',Expenses:'Record shop expenses and monitor costs.','Sales History':'Invoices, payments, customers and refunds.',Reports:'Sales, profit, inventory and payment reporting.',Settings:'Shop details, receipt, currency and user settings.'}[page];if(page==='Reports')return <><Head title="Reports" sub={sub}/><div className="cards"><Metric t="Sales" v={money(sales.reduce((a,s)=>a+s.total,0))}/><Metric t="Gross Profit" v={money(sales.reduce((a,s)=>a+s.total-s.cost,0))}/><Metric t="Expenses" v={money(expenses.reduce((a,e)=>a+e.amount,0))}/><Metric t="Net Profit" v={money(sales.reduce((a,s)=>a+s.total-s.cost,0)-expenses.reduce((a,e)=>a+e.amount,0))}/></div><div className="grid2"><div className="panel"><h2>Inventory Report</h2><p>Stock value: <b>{money(products.reduce((a,p)=>a+p.stock*p.cost,0))}</b></p><p>Low stock: <b>{products.filter(p=>p.stock<=p.min).length}</b></p><p>Out of stock: <b>{products.filter(p=>p.stock<=0).length}</b></p></div><div className="panel"><h2>Profit Report</h2><p>Sales minus product cost and recorded expenses.</p></div></div></>;return <><Head title={title} sub={sub}/><div className="panel placeholder"><div className="bigicon"><Store/></div><h2>{title}</h2><p>This module is included in the SmartPOS V2 architecture and database. The production version connects this screen to Supabase for live cloud data.</p><div className="featurelist"><span>✓ Search & filters</span><span>✓ Role permissions</span><span>✓ Cloud database model</span><span>✓ Export-ready data</span></div>{page==='Expenses'&&<button className="primary" onClick={()=>setExpenses(v=>[...v,{amount:5000,category:'Other'}])}>Add Sample Expense</button>}</div></>}
function ReceiptView({s,money}){return <div className="receipt"><h2>SMARTPOS</h2><p>Professional Retail POS</p><hr/><p>Invoice: {s.id}<br/>{s.date.toLocaleString()}<br/>Customer: {s.customer}</p>{s.items.map(i=><div className="rline" key={i.id}><span>{i.name} × {i.qty}</span><b>{money(i.price*i.qty)}</b></div>)}<hr/><div className="rline"><span>Subtotal</span><b>{money(s.subtotal)}</b></div><div className="rline"><span>Discount</span><b>-{money(s.discount)}</b></div><div className="rline big"><span>TOTAL</span><b>{money(s.total)}</b></div><p>Payment: {s.payment}<br/>Cash: {money(s.cash)}<br/>Change: {money(s.change)}</p><hr/><p>Thank you for your business!</p></div>}
function Modal({title,close,children}){return <div className="modalback"><div className="modal"><div className="modalhead"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
